import { AuthProvider } from "@/app/providers/auth-provider"
import { LiveSupportWidget } from "@/components/live-support/live-support-widget"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <AuthProvider>
      {children}
      <LiveSupportWidget />
    </AuthProvider>
  )
}
